spring:
  datasource:
    url: jdbc:h2:mem:demo;
    username: sa
    password:
    driver-class-name: org.h2.Driver

jwt:
  secret: devhappydayhappydayhappydayhappydayhappydayhappydayhappydayhappydayhappyday

order_service:
  url: http://order-service/order-service/%s/orders
